spring:
  application:
    name: pos-order
  data:
    mongodb:
      host: "localhost"
      port: 27017
      database: "Order"

server:
  port: 8084

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
